"""Add content translations table for multilingual support

Revision ID: 13c674603dc9
Revises: 809b91e133b4
Create Date: 2025-08-11 11:00:50.217379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c674603dc9'
down_revision = '809b91e133b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_content_field', 'content_translations', ['content_type', 'content_id', 'field_name'], unique=False)
    op.create_index('idx_content_language', 'content_translations', ['content_type', 'content_id', 'language_code'], unique=False)
    op.create_index('idx_language_type', 'content_translations', ['language_code', 'content_type'], unique=False)
    op.create_index(op.f('ix_content_translations_id'), 'content_translations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_translations_id'), table_name='content_translations')
    op.drop_index('idx_language_type', table_name='content_translations')
    op.drop_index('idx_content_language', table_name='content_translations')
    op.drop_index('idx_content_field', table_name='content_translations')
    op.drop_table('content_translations')
    # ### end Alembic commands ###