"""remove_unused_url_columns

Revision ID: 2d0bbaac408c
Revises: cbb59697241b
Create Date: 2025-08-22 00:44:53.330815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0bbaac408c'
down_revision = 'cbb59697241b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('about', 'photo_url')
    op.drop_column('contact', 'cv_file_url')
    op.drop_column('projects', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('image_url', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True))
    op.add_column('contact', sa.Column('cv_file_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('about', sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###