"""Add hero_description and job_title fields to about table

Revision ID: 483063a3ebc7
Revises: 8671d66ad488
Create Date: 2025-08-15 09:17:12.454274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483063a3ebc7'
down_revision = '8671d66ad488'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('hero_description_en', sa.Text(), nullable=True))
    op.add_column('about', sa.Column('hero_description_es', sa.Text(), nullable=True))
    op.add_column('about', sa.Column('job_title_en', sa.String(), nullable=True))
    op.add_column('about', sa.Column('job_title_es', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('about', 'job_title_es')
    op.drop_column('about', 'job_title_en')
    op.drop_column('about', 'hero_description_es')
    op.drop_column('about', 'hero_description_en')
    # ### end Alembic commands ###