"""add_active_flags_and_cv_field

Revision ID: 4bcf188bd080
Revises: 764c51636101
Create Date: 2025-08-11 22:31:09.340955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bcf188bd080'
down_revision = 'a3e3c1c7643a'
branch_labels = None
depends_on = None


def safe_drop_column(table_name, column_name):
    """Safely drop a column only if it exists."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Check if table exists first
    if table_name not in inspector.get_table_names():
        return
        
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    if column_name in columns:
        op.drop_column(table_name, column_name)

def safe_add_column(table_name, column_name, column_def):
    """Safely add a column only if it doesn't exist."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Check if table exists first
    if table_name not in inspector.get_table_names():
        return
        
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    if column_name not in columns:
        op.add_column(table_name, column_def)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # About table updates
    safe_add_column('about', 'last_name', sa.Column('last_name', sa.String(), nullable=False, server_default=''))
    safe_add_column('about', 'birth_month', sa.Column('birth_month', sa.Integer(), nullable=True))
    safe_add_column('about', 'birth_year', sa.Column('birth_year', sa.Integer(), nullable=True))
    safe_add_column('about', 'extra_content_en', sa.Column('extra_content_en', sa.Text(), nullable=True))
    safe_add_column('about', 'extra_content_es', sa.Column('extra_content_es', sa.Text(), nullable=True))
    safe_add_column('about', 'created_at', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    
    # Remove server_default after adding column with data
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    about_columns = [col['name'] for col in inspector.get_columns('about')]
    if 'last_name' in about_columns:
        op.alter_column('about', 'last_name', server_default=None)
    
    safe_drop_column('about', 'personal_statement_en')
    safe_drop_column('about', 'age')
    safe_drop_column('about', 'personal_statement_es')
    
    # Contact table updates
    safe_add_column('contact', 'cv_file_url', sa.Column('cv_file_url', sa.String(), nullable=True))
    safe_add_column('contact', 'created_at', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    
    # Add active flags with default True values
    safe_add_column('education', 'activo', sa.Column('activo', sa.Boolean(), nullable=False, server_default='true'))
    safe_add_column('experience', 'activo', sa.Column('activo', sa.Boolean(), nullable=False, server_default='true'))
    safe_add_column('projects', 'activa', sa.Column('activa', sa.Boolean(), nullable=False, server_default='true'))
    safe_add_column('skills', 'activa', sa.Column('activa', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'activa')
    op.drop_column('projects', 'activa')
    op.drop_column('experience', 'activo')
    op.drop_column('education', 'activo')
    op.drop_column('contact', 'created_at')
    op.drop_column('contact', 'cv_file_url')
    op.add_column('about', sa.Column('personal_statement_es', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('about', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('about', sa.Column('personal_statement_en', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('about', 'created_at')
    op.drop_column('about', 'extra_content_es')
    op.drop_column('about', 'extra_content_en')
    op.drop_column('about', 'birth_year')
    op.drop_column('about', 'birth_month')
    op.drop_column('about', 'last_name')
    # ### end Alembic commands ###