"""add_active_flags_and_cv_field

Revision ID: 4bcf188bd080
Revises: 764c51636101
Create Date: 2025-08-11 22:31:09.340955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bcf188bd080'
down_revision = '764c51636101'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # About table updates
    op.add_column('about', sa.Column('last_name', sa.String(), nullable=False, server_default=''))
    op.add_column('about', sa.Column('birth_month', sa.Integer(), nullable=True))
    op.add_column('about', sa.Column('birth_year', sa.Integer(), nullable=True))
    op.add_column('about', sa.Column('extra_content_en', sa.Text(), nullable=True))
    op.add_column('about', sa.Column('extra_content_es', sa.Text(), nullable=True))
    op.add_column('about', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    
    # Remove server_default after adding column with data
    op.alter_column('about', 'last_name', server_default=None)
    
    op.drop_column('about', 'personal_statement_en')
    op.drop_column('about', 'age')
    op.drop_column('about', 'personal_statement_es')
    
    # Contact table updates
    op.add_column('contact', sa.Column('cv_file_url', sa.String(), nullable=True))
    op.add_column('contact', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    
    # Add active flags with default True values
    op.add_column('education', sa.Column('activo', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('experience', sa.Column('activo', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('projects', sa.Column('activa', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('skills', sa.Column('activa', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'activa')
    op.drop_column('projects', 'activa')
    op.drop_column('experience', 'activo')
    op.drop_column('education', 'activo')
    op.drop_column('contact', 'created_at')
    op.drop_column('contact', 'cv_file_url')
    op.add_column('about', sa.Column('personal_statement_es', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('about', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('about', sa.Column('personal_statement_en', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('about', 'created_at')
    op.drop_column('about', 'extra_content_es')
    op.drop_column('about', 'extra_content_en')
    op.drop_column('about', 'birth_year')
    op.drop_column('about', 'birth_month')
    op.drop_column('about', 'last_name')
    # ### end Alembic commands ###