"""Add social media metadata fields to site_config

Revision ID: 5a8b9c2d1e3f
Revises: 4bcf188bd080
Create Date: 2025-01-20 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8b9c2d1e3f'
down_revision = '4bcf188bd080'
branch_labels = None
depends_on = None


def safe_add_column(table_name, column_name, column_def):
    """Safely add a column only if it doesn't exist."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Check if table exists first
    if table_name not in inspector.get_table_names():
        return
        
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    if column_name not in columns:
        op.add_column(table_name, column_def)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add Open Graph metadata fields
    safe_add_column('site_config', 'og_title', sa.Column('og_title', sa.String(length=200), nullable=True, comment="Open Graph title for social sharing"))
    safe_add_column('site_config', 'og_description', sa.Column('og_description', sa.String(length=500), nullable=True, comment="Open Graph description for social sharing"))
    safe_add_column('site_config', 'og_image', sa.Column('og_image', sa.String(length=500), nullable=True, comment="Open Graph image URL for social sharing"))
    safe_add_column('site_config', 'og_url', sa.Column('og_url', sa.String(length=300), nullable=True, comment="Canonical URL for Open Graph"))
    safe_add_column('site_config', 'og_type', sa.Column('og_type', sa.String(length=50), nullable=True, server_default='website', comment="Open Graph type (website, profile, etc.)"))
    
    # Add Twitter Card metadata fields
    safe_add_column('site_config', 'twitter_card', sa.Column('twitter_card', sa.String(length=50), nullable=True, server_default='summary_large_image', comment="Twitter card type"))
    safe_add_column('site_config', 'twitter_site', sa.Column('twitter_site', sa.String(length=100), nullable=True, comment="Twitter @username for website"))
    safe_add_column('site_config', 'twitter_creator', sa.Column('twitter_creator', sa.String(length=100), nullable=True, comment="Twitter @username for creator"))
    safe_add_column('site_config', 'twitter_title', sa.Column('twitter_title', sa.String(length=200), nullable=True, comment="Twitter card title"))
    safe_add_column('site_config', 'twitter_description', sa.Column('twitter_description', sa.String(length=500), nullable=True, comment="Twitter card description"))
    safe_add_column('site_config', 'twitter_image', sa.Column('twitter_image', sa.String(length=500), nullable=True, comment="Twitter card image URL"))
    
    # Add social media links
    safe_add_column('site_config', 'facebook_url', sa.Column('facebook_url', sa.String(length=300), nullable=True, comment="Facebook page URL"))
    safe_add_column('site_config', 'instagram_url', sa.Column('instagram_url', sa.String(length=300), nullable=True, comment="Instagram profile URL"))
    safe_add_column('site_config', 'linkedin_url', sa.Column('linkedin_url', sa.String(length=300), nullable=True, comment="LinkedIn profile URL"))
    safe_add_column('site_config', 'youtube_url', sa.Column('youtube_url', sa.String(length=300), nullable=True, comment="YouTube channel URL"))
    
    # Add SEO and Analytics fields
    safe_add_column('site_config', 'google_analytics_id', sa.Column('google_analytics_id', sa.String(length=50), nullable=True, comment="Google Analytics tracking ID"))
    safe_add_column('site_config', 'google_site_verification', sa.Column('google_site_verification', sa.String(length=100), nullable=True, comment="Google Search Console verification code"))
    
    # Add additional metadata fields
    safe_add_column('site_config', 'author', sa.Column('author', sa.String(length=100), nullable=True, comment="Default author name"))
    safe_add_column('site_config', 'copyright_text', sa.Column('copyright_text', sa.String(length=200), nullable=True, comment="Copyright notice"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: This will only work if columns exist
    try:
        op.drop_column('site_config', 'copyright_text')
    except:
        pass
    try:
        op.drop_column('site_config', 'author')
    except:
        pass
    try:
        op.drop_column('site_config', 'google_site_verification')
    except:
        pass
    try:
        op.drop_column('site_config', 'google_analytics_id')
    except:
        pass
    try:
        op.drop_column('site_config', 'youtube_url')
    except:
        pass
    try:
        op.drop_column('site_config', 'linkedin_url')
    except:
        pass
    try:
        op.drop_column('site_config', 'instagram_url')
    except:
        pass
    try:
        op.drop_column('site_config', 'facebook_url')
    except:
        pass
    try:
        op.drop_column('site_config', 'twitter_image')
    except:
        pass
    try:
        op.drop_column('site_config', 'twitter_description')
    except:
        pass
    try:
        op.drop_column('site_config', 'twitter_title')
    except:
        pass
    try:
        op.drop_column('site_config', 'twitter_creator')
    except:
        pass
    try:
        op.drop_column('site_config', 'twitter_site')
    except:
        pass
    try:
        op.drop_column('site_config', 'twitter_card')
    except:
        pass
    try:
        op.drop_column('site_config', 'og_type')
    except:
        pass
    try:
        op.drop_column('site_config', 'og_url')
    except:
        pass
    try:
        op.drop_column('site_config', 'og_image')
    except:
        pass
    try:
        op.drop_column('site_config', 'og_description')
    except:
        pass
    try:
        op.drop_column('site_config', 'og_title')
    except:
        pass
    # ### end Alembic commands ###