"""Add sender_name field to contact table

Revision ID: 6e6b0ef8870d
Revises: 5bb105fc763c
Create Date: 2025-09-01 19:19:01.501981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e6b0ef8870d'
down_revision = '5bb105fc763c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('sender_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'sender_name')
    # ### end Alembic commands ###