"""Refactor skills: add skill_categories table and update skills structure

Revision ID: 72f253e55880
Revises: 483063a3ebc7
Create Date: 2025-08-15 09:55:54.913154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f253e55880'
down_revision = '483063a3ebc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('label_en', sa.String(), nullable=False),
    sa.Column('label_es', sa.String(), nullable=True),
    sa.Column('icon_name', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_categories_id'), 'skill_categories', ['id'], unique=False)
    op.create_index(op.f('ix_skill_categories_slug'), 'skill_categories', ['slug'], unique=True)
    
    # Insert default skill categories
    connection = op.get_bind()
    connection.execute(sa.text("""
        INSERT INTO skill_categories (slug, label_en, label_es, icon_name, display_order, active) VALUES
        ('web', 'Web Development', 'Desarrollo Web', 'Globe', 1, true),
        ('tools', 'Tools', 'Herramientas', 'Wrench', 2, true),
        ('infrastructure', 'Infrastructure', 'Infraestructura', 'Server', 3, true),
        ('learning', 'Learning', 'Aprendiendo', 'BookOpen', 4, true),
        ('interpersonal', 'Interpersonal', 'Interpersonal', 'Users', 5, true)
    """))
    
    # Add new columns to skills table with temporary nullable constraints
    op.add_column('skills', sa.Column('name_en', sa.String(), nullable=True))  # Temporarily nullable
    op.add_column('skills', sa.Column('name_es', sa.String(), nullable=True))
    op.add_column('skills', sa.Column('category_id', sa.Integer(), nullable=True))  # Temporarily nullable
    op.add_column('skills', sa.Column('icon_name', sa.String(), nullable=True))  # Temporarily nullable
    op.add_column('skills', sa.Column('color', sa.String(), nullable=True))
    op.add_column('skills', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('skills', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    
    # Migrate existing data
    connection.execute(sa.text("""
        UPDATE skills SET 
            name_en = name,
            name_es = name,
            category_id = CASE 
                WHEN category = 'web_development' THEN (SELECT id FROM skill_categories WHERE slug = 'web')
                WHEN category = 'tools' THEN (SELECT id FROM skill_categories WHERE slug = 'tools')
                WHEN category = 'infrastructure' THEN (SELECT id FROM skill_categories WHERE slug = 'infrastructure')
                WHEN category = 'learning' THEN (SELECT id FROM skill_categories WHERE slug = 'learning')
                WHEN category = 'interpersonal' THEN (SELECT id FROM skill_categories WHERE slug = 'interpersonal')
                ELSE (SELECT id FROM skill_categories WHERE slug = 'web')  -- Default fallback
            END,
            icon_name = 'Code',  -- Default icon
            active = activa
    """))
    
    # Now make the required columns non-nullable
    op.alter_column('skills', 'name_en', nullable=False)
    op.alter_column('skills', 'category_id', nullable=False)
    op.alter_column('skills', 'icon_name', nullable=False)
    
    op.create_foreign_key(None, 'skills', 'skill_categories', ['category_id'], ['id'])
    op.drop_column('skills', 'name')
    op.drop_column('skills', 'activa')
    op.drop_column('skills', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('skills', sa.Column('activa', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('skills', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_column('skills', 'updated_at')
    op.drop_column('skills', 'active')
    op.drop_column('skills', 'color')
    op.drop_column('skills', 'icon_name')
    op.drop_column('skills', 'category_id')
    op.drop_column('skills', 'name_es')
    op.drop_column('skills', 'name_en')
    op.drop_index(op.f('ix_skill_categories_slug'), table_name='skill_categories')
    op.drop_index(op.f('ix_skill_categories_id'), table_name='skill_categories')
    op.drop_table('skill_categories')
    # ### end Alembic commands ###