"""Add password_hash column to users

Revision ID: 809b91e133b4
Revises: 3397abbe2eec
Create Date: 2025-08-11 01:00:27.703686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809b91e133b4'
down_revision = '3397abbe2eec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add column as nullable
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    
    # Update existing users with a temporary password hash
    # This is for the existing admin user - they'll need to be updated with real password
    op.execute("UPDATE users SET password_hash = '$2b$12$temp.hash.for.migration' WHERE password_hash IS NULL")
    
    # Now make the column NOT NULL
    op.alter_column('users', 'password_hash', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###