"""Add site_config table and modify about table structure

Revision ID: 8671d66ad488
Revises: b85f4e27e56b
Create Date: 2025-08-15 02:36:41.798860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8671d66ad488'
down_revision = '809b91e133b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_title', sa.String(length=200), nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=False),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('meta_keywords', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_config_id'), 'site_config', ['id'], unique=False)
    op.create_index(op.f('ix_site_config_site_title'), 'site_config', ['site_title'], unique=False)
    # Drop content_translations table and indexes if they exist
    try:
        op.drop_index('idx_content_field', table_name='content_translations')
    except:
        pass
    try:
        op.drop_index('idx_content_language', table_name='content_translations')
    except:
        pass
    try:
        op.drop_index('idx_language_type', table_name='content_translations')
    except:
        pass
    try:
        op.drop_index('ix_content_translations_id', table_name='content_translations')
    except:
        pass
    try:
        op.drop_table('content_translations')
    except:
        pass
    op.add_column('about', sa.Column('birth_date', sa.Date(), nullable=True))
    try:
        op.drop_column('about', 'birth_month')
    except:
        pass
    try:
        op.drop_column('about', 'extra_content_en')
    except:
        pass
    try:
        op.drop_column('about', 'extra_content_es')
    except:
        pass
    try:
        op.drop_column('about', 'birth_year')
    except:
        pass
    op.alter_column('education', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('experience', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('projects', 'activa',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('skills', 'activa',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skills', 'activa',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('projects', 'activa',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('experience', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('education', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('about', sa.Column('birth_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('about', sa.Column('extra_content_es', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('about', sa.Column('extra_content_en', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('about', sa.Column('birth_month', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('about', 'birth_date')
    op.create_table('content_translations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language_code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('translated_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='content_translations_pkey')
    )
    op.create_index('ix_content_translations_id', 'content_translations', ['id'], unique=False)
    op.create_index('idx_language_type', 'content_translations', ['language_code', 'content_type'], unique=False)
    op.create_index('idx_content_language', 'content_translations', ['content_type', 'content_id', 'language_code'], unique=False)
    op.create_index('idx_content_field', 'content_translations', ['content_type', 'content_id', 'field_name'], unique=False)
    op.drop_index(op.f('ix_site_config_site_title'), table_name='site_config')
    op.drop_index(op.f('ix_site_config_id'), table_name='site_config')
    op.drop_table('site_config')
    # ### end Alembic commands ###