"""Remove is_in_progress column from skills table

Revision ID: 9752015bd799
Revises: 72f253e55880
Create Date: 2025-08-15 14:14:32.694507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9752015bd799'
down_revision = 'd384c71f3ccd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists before dropping
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    skills_columns = [col['name'] for col in inspector.get_columns('skills')]
    
    if 'is_in_progress' in skills_columns:
        op.drop_column('skills', 'is_in_progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('is_in_progress', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###