"""fix_string_lengths_for_sqladmin

Revision ID: a3e3c1c7643a
Revises: eb34a9f87720
Create Date: 2025-08-19 09:13:17.330607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e3c1c7643a'
down_revision = 'eb34a9f87720'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('skills_category_id_fkey', 'skills', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('skills_category_id_fkey', 'skills', 'skill_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###