"""restore_foreign_keys_in_skills

Revision ID: a5c1e7c7d003
Revises: a3e3c1c7643a
Create Date: 2025-08-19 09:39:08.289136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c1e7c7d003'
down_revision = 'eb34a9f87720'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'skills', 'skill_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='foreignkey')
    # ### end Alembic commands ###