"""update_models_remove_translations_and_fields

Revision ID: b85f4e27e56b
Revises: 4bcf188bd080
Create Date: 2025-08-11 22:49:56.253269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85f4e27e56b'
down_revision = '4bcf188bd080'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Education: remove gpa column
    op.drop_column('education', 'gpa')
    
    # Projects: remove is_featured column
    op.drop_column('projects', 'is_featured')
    
    # Skills: consolidate name fields - migrate data from name_en to name
    op.add_column('skills', sa.Column('name', sa.String(), nullable=True))
    # Migrate data from name_en to name
    op.execute("UPDATE skills SET name = name_en WHERE name_en IS NOT NULL")
    # Make name column not nullable after data migration
    op.alter_column('skills', 'name', nullable=False)
    # Drop the old name columns
    op.drop_column('skills', 'name_es')
    op.drop_column('skills', 'name_en')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('name_en', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('skills', sa.Column('name_es', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('skills', 'activa',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('skills', 'name')
    op.add_column('projects', sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('projects', 'activa',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('experience', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('education', sa.Column('gpa', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('education', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###