"""remove_field_of_study_and_description_from_education

Revision ID: c81447923a67
Revises: d6e931d2de31
Create Date: 2025-08-21 00:19:20.715737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81447923a67'
down_revision = 'd6e931d2de31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns exist before dropping them
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('education')]
    
    if 'field_of_study_es' in columns:
        op.drop_column('education', 'field_of_study_es')
    if 'description_en' in columns:
        op.drop_column('education', 'description_en')
    if 'field_of_study_en' in columns:
        op.drop_column('education', 'field_of_study_en')
    if 'description_es' in columns:
        op.drop_column('education', 'description_es')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('description_es', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('field_of_study_en', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('description_en', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('field_of_study_es', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###