"""add_file_upload_fields

Revision ID: cbb59697241b
Revises: c81447923a67
Create Date: 2025-08-21 18:01:55.610396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb59697241b'
down_revision = 'c81447923a67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('photo_file', sa.String(500), nullable=True))
    op.add_column('contact', sa.Column('cv_file', sa.String(500), nullable=True))
    op.add_column('projects', sa.Column('image_file', sa.String(500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'image_file')
    op.drop_column('contact', 'cv_file')
    op.drop_column('about', 'photo_file')
    # ### end Alembic commands ###