"""fix_nationality_defaults

Revision ID: d384c71f3ccd
Revises: 427200ffd139
Create Date: 2025-08-11 15:01:38.329466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd384c71f3ccd'
down_revision = '427200ffd139'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###