"""remove_unnecessary_social_media_fields

Revision ID: d6e931d2de31
Revises: 5a8b9c2d1e3f
Create Date: 2025-08-20 23:35:30.789181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e931d2de31'
down_revision = '5a8b9c2d1e3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_config', 'google_site_verification')
    op.drop_column('site_config', 'author')
    op.drop_column('site_config', 'copyright_text')
    op.drop_column('site_config', 'linkedin_url')
    op.drop_column('site_config', 'facebook_url')
    op.drop_column('site_config', 'google_analytics_id')
    op.drop_column('site_config', 'instagram_url')
    op.drop_column('site_config', 'youtube_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_config', sa.Column('youtube_url', sa.VARCHAR(length=300), autoincrement=False, nullable=True, comment='YouTube channel URL'))
    op.add_column('site_config', sa.Column('instagram_url', sa.VARCHAR(length=300), autoincrement=False, nullable=True, comment='Instagram profile URL'))
    op.add_column('site_config', sa.Column('google_analytics_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Google Analytics tracking ID'))
    op.add_column('site_config', sa.Column('facebook_url', sa.VARCHAR(length=300), autoincrement=False, nullable=True, comment='Facebook page URL'))
    op.add_column('site_config', sa.Column('linkedin_url', sa.VARCHAR(length=300), autoincrement=False, nullable=True, comment='LinkedIn profile URL'))
    op.add_column('site_config', sa.Column('copyright_text', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='Copyright notice'))
    op.add_column('site_config', sa.Column('author', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Default author name'))
    op.add_column('site_config', sa.Column('google_site_verification', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Google Search Console verification code'))
    # ### end Alembic commands ###