"""restore_foreign_key_constraint_for_skills

Revision ID: eb34a9f87720
Revises: 9752015bd799
Create Date: 2025-08-19 00:19:09.179651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb34a9f87720'
down_revision = '764c51636101'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###