"""update_site_config_and_contact_models

Revision ID: f61113e4cea4
Revises: 2d0bbaac408c
Create Date: 2025-08-22 02:10:00.975337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f61113e4cea4'
down_revision = '2d0bbaac408c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'phone')
    op.drop_column('contact', 'twitter_url')
    op.drop_column('contact', 'instagram_url')
    op.add_column('site_config', sa.Column('favicon_file', sa.String(length=500), nullable=True, comment='Favicon file path'))
    op.add_column('site_config', sa.Column('og_image_file', sa.String(length=500), nullable=True, comment='Open Graph image file path'))
    op.add_column('site_config', sa.Column('twitter_image_file', sa.String(length=500), nullable=True, comment='Twitter card image file path'))
    op.drop_column('site_config', 'og_image')
    op.drop_column('site_config', 'twitter_image')
    op.drop_column('site_config', 'twitter_creator')
    op.drop_column('site_config', 'twitter_site')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_config', sa.Column('twitter_site', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Twitter @username for website'))
    op.add_column('site_config', sa.Column('twitter_creator', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Twitter @username for creator'))
    op.add_column('site_config', sa.Column('twitter_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Twitter card image URL'))
    op.add_column('site_config', sa.Column('og_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Open Graph image URL for social sharing'))
    op.drop_column('site_config', 'twitter_image_file')
    op.drop_column('site_config', 'og_image_file')
    op.drop_column('site_config', 'favicon_file')
    op.add_column('contact', sa.Column('instagram_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contact', sa.Column('twitter_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contact', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###