name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.11"

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_portfolio_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt

    - name: Set up environment variables
      run: |
        echo "DATABASE_URL=postgresql://test_user:test_password@localhost:5432/test_portfolio_db" >> $GITHUB_ENV
        echo "SECRET_KEY=test-secret-key-for-ci" >> $GITHUB_ENV
        echo "GOOGLE_CLIENT_ID=test-client-id" >> $GITHUB_ENV
        echo "GOOGLE_CLIENT_SECRET=test-client-secret" >> $GITHUB_ENV
        echo "DEBUG=True" >> $GITHUB_ENV

    - name: Run database migrations
      run: |
        alembic upgrade head

    - name: Run linting
      run: |
        pip install flake8 black isort
        # Check code formatting
        black --check .
        # Check import sorting
        isort --check-only .
        # Check code style
        flake8 app tests

    - name: Run type checking
      run: |
        pip install mypy
        mypy app --ignore-missing-imports

    - name: Run tests
      run: |
        pytest --cov=app --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella

  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install security scanning tools
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety

    - name: Run security scans
      run: |
        # Check for security vulnerabilities in dependencies
        safety check
        # Check for security issues in code
        bandit -r app/ -f json -o bandit-report.json || true
        
    - name: Upload security scan results
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: bandit-report.json

  build:
    runs-on: ubuntu-latest
    needs: [test, security]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t portfolio-backend:${{ github.sha }} .
        docker build -f Dockerfile.prod -t portfolio-backend:prod-${{ github.sha }} .

    - name: Test Docker image
      run: |
        # Test that the image can start
        docker run --rm -d --name test-container \
          -e DATABASE_URL=sqlite:///test.db \
          -e SECRET_KEY=test-key \
          -e GOOGLE_CLIENT_ID=test \
          -e GOOGLE_CLIENT_SECRET=test \
          -p 8001:8000 \
          portfolio-backend:${{ github.sha }}
        
        # Wait for container to start
        sleep 10
        
        # Test health endpoint
        curl -f http://localhost:8001/health || exit 1
        
        # Cleanup
        docker stop test-container

    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag portfolio-backend:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:latest
        docker tag portfolio-backend:prod-${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:prod-latest
        docker push ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:prod-latest

  deploy-staging:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/develop'
    environment: staging
    
    steps:
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment..."
        # Add your staging deployment commands here
        # This could be SSH to server, kubectl apply, etc.

  deploy-production:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - name: Deploy to production
      run: |
        echo "Deploying to production environment..."
        # Add your production deployment commands here
        # This could be SSH to server, kubectl apply, etc.