name: Security

on:
  schedule:
    # Run security scans weekly
    - cron: '0 2 * * 0'
  push:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit

    - name: Check dependencies for vulnerabilities
      run: |
        safety check || true

    - name: Check code for security issues
      run: |
        bandit -r app/ || true

    - name: Check for secrets
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        # Use full filesystem scan instead of git diff to avoid base=head issue
        extra_args: --only-verified